const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Behaviors.Orbit,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Health: 0},
	{Car: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{BulletGreen: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Audio: 0},
	{RedTank: 0},
	{Fade: 0},
	{Explosion: 0},
	{Barricade: 0},
	{Fire: 0},
	{BulletRed: 0},
	{FenceRed: 0},
	{Orbit: 0},
	{Turret: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	BulletGreen: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	RedTank: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Barricade: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	BulletRed: class extends self.ISpriteInstance {},
	FenceRed: class extends self.ISpriteInstance {},
	Turret: class extends self.ISpriteInstance {}
}